image: maven:3.9.14-eclipse-temurin-25

variables :
  MAVEN_OPTS: "-Dmaven.repo.local=$CI_PROJECT_DIR/.m2/repository"

stages:
  - build
  - upload
  - release

cache :
  paths :
    - .m2/repository

build_job:
  stage: build
  script:
    - mvn clean package -DskipTests
  artifacts:
    paths:
      - target/*.exe
      - target/*.jar

upload_exe_to_registry :
  stage: upload
  image: curlimages/curl:latest
  rules:
    - if: $CI_COMMIT_TAG
  dependencies:
    - build_job
  script :
  - |
      curl --header "JOB-TOKEN: ${CI_JOB_TOKEN}" \
           --upload-file target/Nukepad.exe \
           "${CI_API_V4_URL}/projects/${CI_PROJECT_ID}/packages/generic/Nukepad/${CI_COMMIT_TAG}/Nukepad.exe"

create_release:
  stage: release
  image: curlimages/curl:latest
  rules:
    - if: $CI_COMMIT_TAG
  script:
    - echo "Creating release for tag $CI_COMMIT_TAG"
  release:
    tag_name: '$CI_COMMIT_TAG'
    name: 'Release $CI_COMMIT_TAG'
    description: 'Automatic release created from pipeline for tag $CI_COMMIT_TAG'
    assets:
      links:
        - name: 'Nukepad.exe'
          url: '${CI_API_V4_URL}/projects/${CI_PROJECT_ID}/packages/generic/nukepad/${CI_COMMIT_TAG}/Nukepad.exe'
          link_type: 'package'
